site_name: BlueSky

repo_name: '2024.2-Grupo01'
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo01
# site_url: 
edit_uri: edit/main/docs/

# copyright: Copyright & copy; 2024 Nome do app

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


theme:
  custom_dir: overrides
  name: material
  language: pt-BR

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: custom-icons/contrast-light
        name: Modo Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: custom-icons/contrast-dark
        name: Modo Escuro

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

      options:
        custom_icons:
          - overrides/.icons 

nav:
  - Home: index.md
  - Apresentação:
    - Entrega 1: Apresentacao/entrega1.md
    - Entrega 2: Apresentacao/entrega2.md
    - Entrega 3: Apresentacao/entrega3.md
    - Entrega 4: Apresentacao/entrega4.md
    - Entrega 5: Apresentacao/entrega5.md
    - Entrega 6: Apresentacao/entrega6.md
    - Entrega 7: Apresentacao/entrega7.md
    - Entrega 8: Apresentacao/entrega8.md
  - Atas: 
    - Reunião 1: Atas/reuniao_1.md
    - Reunião 2: Atas/reuniao_2.md
    - Reunião 3: Atas/reuniao_3.md
    - Reunião 4: Atas/reuniao_4.md
    - Reunião 5: Atas/reuniao_5.md
    - Reunião 6: Atas/reuniao_6.md
  - Desenvolvimento:
    - Cronograma: Desenvolvimento/Cronograma.md
    - Ferramentas: Desenvolvimento/ferramentas.md
    - Processo de Desing: Desenvolvimento/ProcessoDesing.md
    - Sites Avaliados: Desenvolvimento/sitesAvaliados.md
    - Site Escolhido: Desenvolvimento/SiteEscolhido.md
    - Disponibilidade dos Integrantes: Desenvolvimento/disponibilidade.md
  - Análise de Requisitos: 
    - Aspectos Éticos: AnaliseRequisitos/AspectosEticos.md
    - Questionario Perfil de Usuário: AnaliseRequisitos/PerfilUser.md
    - Perfil de Usuário: AnaliseRequisitos/Resultado.md
    - Personas: AnaliseRequisitos/Personas.md
    - Cenarios: AnaliseRequisitos/Cenarios.md
    - Analise de tarefas:
      - GOMS: AnaliseRequisitos/GOMS.md
      - HTA: AnaliseRequisitos/HTA.md
    - Princípios Gerais: AnaliseRequisitos/Principios.md
    - Guia de Estilo: AnaliseRequisitos/guia_estilo.md
    - Características Gerais da Plataforma: AnaliseRequisitos/CaracteristicasGerais.md
    - Metas de Usabilidade: AnaliseRequisitos/MetaDeUsabilidade.md
  - Design, Avaliação e Desenvolvimento: 
    - Nível 1: 
      - HTA: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/relato.md
      - Planejamento da avaliação da Análise de Tarefas: DesignAvaliacaoDesenvolvimento/planejamentoAAT.md
      - Avaliação da Análise de Tarefas: DesignAvaliacaoDesenvolvimento/Nivel2/avaliacao_hta.md
      - Planejamento da avaliação do Storyboard: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/planejamentoStory.md
      - Planejamento Resultado da avaliação do Storyboard: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/planejamentoResultStory.md
      - Execução da avaliação do Storyboard: DesignAvaliacaoDesenvolvimento/Nivel2/relatoStory.md
      - Storyboards: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboards.md
      - Execução da avaliação do HTA: DesignAvaliacaoDesenvolvimento/Nivel2/avaliacao_hta.md
    - Nível 2:
      - Planejamento da Avaliação do Protótipo de papel: DesignAvaliacaoDesenvolvimento/Nivel2/prototipoDePapel/planejamento_avaliacao.md
      - Planejamento do Relato do Protótipo de papel: DesignAvaliacaoDesenvolvimento/Nivel2/prototipoDePapel/planejamento_relato.md
      - Protótipo de papel: DesignAvaliacaoDesenvolvimento/Nivel2/papelPrototipo.md
      - Relato do Protótipo de Papel: DesignAvaliacaoDesenvolvimento/Nivel3/Relatopapel.md
    - Nível 3:
      - Planejamento da Avaliação do Protótipo de Alta Fidelidade: DesignAvaliacaoDesenvolvimento/Nivel3/planejamentoProtAlta.md
      - Planejamento do Relato do Protótipo de Alta Fidelidade: DesignAvaliacaoDesenvolvimento/Nivel3/planejamentoRelatoProtAlta.md
    - Nível 4:
      - Relato do protótipo: DesignAvaliacaoDesenvolvimento/Nivel4/relatoAF.md
  - Inspeções:
    - Etapa 1: 
      - Planejamento: Inspecao/planejamento.md
      - Inspeção final: Inspecao/inspecaoFinal.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2.md
    - Etapa 2: 
      - Planejamento: Inspecao/planejamento2.md
      - Inspeção final: Inspecao/inspecaoFinal2.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-2.md
    - Etapa 3: 
      - Planejamento: Inspecao/planejamento3.md
      - Inspeção final: Inspecao/inspecaoFinal3.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-3.md
    - Etapa 4: 
      - Planejamento: Inspecao/planejamento4.md
      - Inspeção final: Inspecao/inspecaoFinal4.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-4.md
    - Etapa 5:
      - Planejamento: Inspecao/Planejamento5.md
      - Inspeção final: Inspecao/inspecaoFinal5.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-5.1.md
    - Etapa 6:
      - Planejamento: Inspecao/planejamento6.md
      - Inspeção final: Inspecao/inspecaoFinal6.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-6.md
    - Etapa 7:
      - Planejamento: Inspecao/planejamento7.md
      - Inspeção final: Inspecao/inspecaoFinal7.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-7.md
  - Verificação e Validação:
    - Planejamento:
      - Análise de Requisitos: 
        # - Características Gerais da Plataforma: Verificacao/planejamento/analise_req/caracteristicas_gerais.md
        - Cenários: Verificacao/planejamento/analise_req/cenarios.md
        - Guia de Estilos: Verificacao/planejamento/analise_req/guia_estilos.md
        - Metas de Usabilidade: Verificacao/planejamento/analise_req/metas_usabilidade.md
        - Personas: Verificacao/planejamento/analise_req/personas.md
        - Elenco de Personas: Verificacao/planejamento/analise_req/elenco_personas.md
        - HTA: Verificacao/planejamento/analise_req/hta.md
        - GOMS: Verificacao/planejamento/analise_req/goms.md
      - Design, Avaliação e Desenvolvimento:
        - Nível 1:
          - Planejamento da Avaliação da Análise de Tarefas: Verificacao/planejamento/design_avaliacao_dev/nivel1/planejamento_avaliacao_tarefas.md
          # - Planejamento do Relato da Análise de Tarefas: Verificacao/planejamento/design_avaliacao_dev/nivel1/planejamento_relato_tarefas.md
          - Execução da Avaliação da Análise de Tarefas: Verificacao/planejamento/design_avaliacao_dev/nivel1/execucao_avaliacao_tarefas.md
          - Storyboard: Verificacao/planejamento/design_avaliacao_dev/nivel1/relato_storyboard.md
          - Planejamento da Avaliação do Storyboard: Verificacao/planejamento/design_avaliacao_dev/nivel1/planejamento_avaliacao_storyboard.md
          - Planejamento do Resultado da Avaliação do Storyboard: Verificacao/planejamento/design_avaliacao_dev/nivel1/planejamento_resultado_storyboard.md
          - Execução da Avaliação do Storyboard: Verificacao/planejamento/design_avaliacao_dev/nivel1/execucao_avaliacao_storyboard.md
        - Nível 2: 
          - Planejamento da Avaliação do Protótipo de papel: Verificacao/planejamento/design_avaliacao_dev/nivel2/planejamento_avaliacao_prototipo_papel.md
          - Planejamento do Relato do Protótipo de papel: Verificacao/planejamento/design_avaliacao_dev/nivel2/planejamento_relato_prototipo_papel.md
        - Nível 3:
          - Planejamento da Avaliação do Protótipo de Alta Fidelidade: Verificacao/planejamento/design_avaliacao_dev/nivel3/planejamento_avaliacao_prototipo_alta.md
          - Planejamento do Relato do Protótipo de Alta Fidelidade: Verificacao/planejamento/design_avaliacao_dev/nivel3/planejamento_relato_prototipo_alta.md
          - Relato do Protótipo de Papel: Verificacao/planejamento/design_avaliacao_dev/nivel3/relato_prototipo_papel.md
        - Nível 4:
          - Protótipo de Alta Fidelidade:  Verificacao/planejamento/design_avaliacao_dev/nivel4/relato_prototipo_alta.md
    - Inpeções:
      - Grupo 1:
        - Entrega 2: Verificacao/inspecao/grupo1/entrega2.md
        - Entrega 3: Verificacao/inspecao/grupo1/entrega3.md
        - Entrega 4: Verificacao/inspecao/grupo1/entrega4.md
        - Entrega 5: Verificacao/inspecao/grupo1/entrega5.md
        - Entrega 6: Verificacao/inspecao/grupo1/entrega6.md
        - Entrega 7: Verificacao/inspecao/grupo1/entrega7.md
      - Grupo 2:
        - Entrega 2: Verificacao/inspecao/grupo2/entrega2.md
        - Entrega 3: Verificacao/inspecao/grupo2/entrega3.md
        - Entrega 4: Verificacao/inspecao/grupo2/entrega4.md
        - Entrega 5: Verificacao/inspecao/grupo2/entrega5.md
        - Entrega 6: Verificacao/inspecao/grupo2/entrega6.md
        - Entrega 7: Verificacao/inspecao/grupo2/entrega7.md
  - Entrega Final:
      - Site Selecionado: EntregaFinal/SiteSelecionado.md
      - Ciclo de vida escolhido: EntregaFinal/CicloVidaEscolhido.md
      - Apresentações do grupo: EntregaFinal/Entregas.md
      - Ferramentas utilizadas: EntregaFinal/FerramentasResumo.md
      - Feedback do grupo: EntregaFinal/AvaliacaoGrupo.md
      - Planejamento das entregas: EntregaFinal/PlanejamentoDosRecursos.md
      - Avaliação de protótipos: EntregaFinal\Sintese-Avaliacao.md
    
    

