site_name: BlueSky

repo_name: '2024.2-Grupo01'
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo01
# site_url: 
edit_uri: edit/main/docs/

# copyright: Copyright & copy; 2024 Nome do app

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


theme:
  custom_dir: overrides
  name: material
  language: pt-BR

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: custom-icons/contrast-light
        name: Modo Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: custom-icons/contrast-dark
        name: Modo Escuro

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

      options:
        custom_icons:
          - overrides/.icons 

nav:
  - Home: index.md
  - Apresentação:
    - Entrega 1: Apresentacao/entrega1.md
    - Entrega 2: Apresentacao/entrega2.md
    - Entrega 3: Apresentacao/entrega3.md
    - Entrega 4: Apresentacao/entrega4.md
  - Atas: 
    - Reunião 1: Atas/reuniao_1.md
    - Reunião 2: Atas/reuniao_2.md
  - Desenvolvimento:
    - Cronograma: Desenvolvimento/Cronograma.md
    - Ferramentas: Desenvolvimento/ferramentas.md
    - Processo de Desing: Desenvolvimento/ProcessoDesing.md
    - Sites Avaliados: Desenvolvimento/sitesAvaliados.md
    - Site Escolhido: Desenvolvimento/SiteEscolhido.md
    - Disponibilidade dos Integrantes: Desenvolvimento/disponibilidade.md
  - Análise de Requisitos: 
    - Aspectos Éticos: AnaliseRequisitos/AspectosEticos.md
    - Questionario Perfil de Usuário: AnaliseRequisitos/PerfilUser.md
    - Perfil de Usuário: AnaliseRequisitos/Resultado.md
    - Personas: AnaliseRequisitos/Personas.md
    - Cenarios: AnaliseRequisitos/Cenarios.md
    - Analise de tarefas:
      - GOMS: AnaliseRequisitos/GOMS.md
      - HTA: AnaliseRequisitos/HTA.md
    - Princípios Gerais: AnaliseRequisitos/Principios.md
    - Guia de Estilo: AnaliseRequisitos/guia_estilo.md
    - Características Gerais da Plataforma: AnaliseRequisitos/CaracteristicasGerais.md
    - Metas de Usabilidade: AnaliseRequisitos/MetaDeUsabilidade.md
  - Design, Avaliação e Desenvolvimento: 
    - Nível 1: 
      - HTA: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/relato.md
      - Planejamento da avaliação do Storyboard: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/planejamentoStory.md
      - Planejamento da avaliação da Análise de Tarefas: DesignAvaliacaoDesenvolvimento/planejamentoAAT.md
      - Planejamento Resultado da avaliação do Storyboard: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/planejamentoResultStory.md
      - Storyboards: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboards.md
    - Nível 2:
      - Planejamento da Avaliação do Protótipo de papel: DesignAvaliacaoDesenvolvimento/Nivel2/prototipoDePapel/planejamento_avaliacao.md
      - Planejamento do Relato do Protótipo de papel: DesignAvaliacaoDesenvolvimento/Nivel2/prototipoDePapel/planejamento_relato.md
      - Execução da avaliação do Storyboard: DesignAvaliacaoDesenvolvimento/Nivel2/relatoStory.md
  - Inspeção:
    - Etapa 1: 
      - Planejamento: Inspecao/planejamento.md
      - Inspeção final: Inspecao/inspecaoFinal.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2.md
    - Etapa 2: 
      - Planejamento: Inspecao/planejamento2.md
      - Inspeção final: Inspecao/inspecaoFinal2.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-2.md
    - Etapa 3: 
      - Planejamento: Inspecao/planejamento3.md
      - Inspeção final: Inspecao/inspecaoFinal3.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-3.md
    - Etapa 4: 
      - Planejamento: Inspecao/planejamento4.md
      - Inspeção final: Inspecao/inspecaoFinal4.md
      - Inspeção Grupo 02: Inspecao/inspecaoGrupo2-4.md
    - Etapa 5:
      - Planejamento: Inspecao/Planejamento5.md
